export const LOCAL_STORAGE_KEY = "adagioTranslate.currentProject.v1";
export const UI_LANGUAGE_STORAGE_KEY = "adagioTranslate.uiLanguage.v1";
export const GOOGLE_API_KEY_STORAGE_KEY = "adagioTranslate.googleApiKey.v1";
export const MYMEMORY_EMAIL_STORAGE_KEY = "adagioTranslate.myMemoryEmail.v1";
export const MT_PROVIDER_STORAGE_KEY = "adagioTranslate.mtProvider.v1";
export const ONBOARDING_STATUS_STORAGE_KEY = "adagioTranslate.onboardingStatus.v1";

export const GOOGLE_TRANSLATE_ENDPOINT = "https://translation.googleapis.com/language/translate/v2";
export const MYMEMORY_TRANSLATE_ENDPOINT = "https://api.mymemory.translated.net/get";

export const LANGUAGE_LABELS = {
  ar: "Arabic",
  bn: "Bengali",
  zh: "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  nl: "Dutch",
  en: "English",
  fr: "French",
  de: "German",
  el: "Greek",
  he: "Hebrew",
  hi: "Hindi",
  id: "Indonesian",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  fa: "Persian",
  pl: "Polish",
  pt: "Portuguese",
  ru: "Russian",
  es: "Spanish",
  sv: "Swedish",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
};

export const LANGUAGE_LABELS_ES = {
  ar: "Árabe",
  bn: "Bengalí",
  zh: "Chino (simplificado)",
  "zh-TW": "Chino (tradicional)",
  nl: "Neerlandés",
  en: "Inglés",
  fr: "Francés",
  de: "Alemán",
  el: "Griego",
  he: "Hebreo",
  hi: "Hindi",
  id: "Indonesio",
  it: "Italiano",
  ja: "Japonés",
  ko: "Coreano",
  fa: "Persa",
  pl: "Polaco",
  pt: "Portugués",
  ru: "Ruso",
  es: "Español",
  sv: "Sueco",
  th: "Tailandés",
  tr: "Turco",
  uk: "Ucraniano",
  ur: "Urdu",
  vi: "Vietnamita",
};

export const UI_TEXT = {
  en: {
    app_title: "Adagio Translate",
    fork_github: "Fork me on GitHub",
    menu_file: "File",
    menu_edit: "Edit",
    menu_view: "View",
    local_settings: "Local Settings",
    new_project: "New Project",
    import_document: "Import Document",
    open_project: "Open Project",
    save_project: "Save Project",
    save_project_as: "Save Project As",
    export_md: "Export Target as Markdown",
    export_docx: "Export Target as DOCX",
    undo: "Undo",
    redo: "Redo",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    select_all: "Select All",
    split_mode: "Split Mode",
    editor_position: "Editor Position",
    sentence: "Sentence",
    paragraph: "Paragraph",
    bottom: "Bottom",
    right: "Right",
    segments: "Segments",
    resegment: "Re-Segment",
    segments_help: "Click a segment to edit its translation inline.",
    segment_count: "{count} segments",
    glossary: "Glossary",
    add_entry: "Add Entry",
    glossary_help: "Relevant entries for selected segment appear here.",
    glossary_no_entries: "No glossary entries yet.",
    glossary_no_matches: "No glossary matches for this segment.",
    glossary_summary_prefix: "Glossary",
    view_all_glossary_matches: "View all glossary matches",
    project_setup: "Project Setup",
    source_language: "Source Language",
    target_language: "Target Language",
    select_source_language: "Select source language",
    select_target_language: "Select target language",
    split_method: "Split Method",
    cancel: "Cancel",
    continue: "Continue",
    add_glossary_entry: "Add Glossary Entry",
    target_term: "Target Term",
    translation_meaning: "Translation / Meaning",
    add: "Add",
    close: "Close",
    glossary_matches: "Glossary Matches",
    local_settings_title: "Local Settings",
    local_settings_note:
      "Machine translation settings and API keys are stored only in this browser and are not included in exported project JSON files.",
    app_language: "App Language",
    translation_provider: "Translation Provider",
    provider_none: "None",
    provider_mymemory: "MyMemory (No account)",
    provider_google: "Google Translate (API key)",
    google_api_key: "Google Cloud API Key",
    mymemory_email: "MyMemory Email (optional)",
    clear_keys: "Clear Keys",
    save_settings: "Save Settings",
    local_settings_saved: "Local settings saved.",
    local_settings_loaded: "Local settings loaded.",
    local_settings_local_notice: "These settings are local to this browser.",
    untitled_project: "Untitled Project",
    no_languages_set: "No languages set",
    target_translation: "Translation",
    write_translation_here: "Write translation here...",
    status_pending: "pending",
    status_translated: "translated",
    status_prefix: "Status",
    auto_translate_segment: "Auto-Translate Segment",
    translating: "Translating...",
    select_segment_first: "Select a segment first.",
    set_languages_first: "Set source and target languages first.",
    configure_mt_first: "Configure machine translation in Local Settings first.",
    selected_segment_no_source: "Selected segment has no source text.",
    requesting_translation: "Requesting translation...",
    segment_translated: "Segment translated.",
    translation_failed: "Translation failed.",
    no_translated_segments: "No segments to export yet.",
    docx_export_unavailable: "DOCX export library is not available. Reload and try again.",
    could_not_export_docx: "Could not export DOCX.",
    project_saved: "Project saved.",
    invalid_project_file: "The selected project file is invalid.",
    empty_document_file: "The selected file has no readable text content.",
    start_new_project_confirm: "Start a new project? Unsaved changes in the current project will be lost.",
    onboarding_header: "Quick Tour",
    onboarding_step_counter: "Step {current} of {total}",
    onboarding_back: "Back",
    onboarding_next: "Next",
    onboarding_finish: "Finish",
    onboarding_skip: "Skip",
  },
  es: {
    app_title: "Adagio Translate",
    fork_github: "Haz un fork en GitHub",
    menu_file: "Archivo",
    menu_edit: "Editar",
    menu_view: "Ver",
    local_settings: "Configuración local",
    new_project: "Nuevo proyecto",
    import_document: "Importar documento",
    open_project: "Abrir proyecto",
    save_project: "Guardar proyecto",
    save_project_as: "Guardar proyecto como",
    export_md: "Exportar destino como Markdown",
    export_docx: "Exportar destino como DOCX",
    undo: "Deshacer",
    redo: "Rehacer",
    cut: "Cortar",
    copy: "Copiar",
    paste: "Pegar",
    select_all: "Seleccionar todo",
    split_mode: "Modo de segmentación",
    editor_position: "Posición del editor",
    sentence: "Oración",
    paragraph: "Párrafo",
    bottom: "Abajo",
    right: "Derecha",
    segments: "Segmentos",
    resegment: "Volver a segmentar",
    segments_help: "Haz clic en un segmento para editar su traducción en línea.",
    segment_count: "{count} segmentos",
    glossary: "Glosario",
    add_entry: "Agregar entrada",
    glossary_help: "Aquí aparecen las entradas relevantes para el segmento seleccionado.",
    glossary_no_entries: "Aún no hay entradas en el glosario.",
    glossary_no_matches: "No hay coincidencias de glosario para este segmento.",
    glossary_summary_prefix: "Glosario",
    view_all_glossary_matches: "Ver todas las coincidencias del glosario",
    project_setup: "Configuración del proyecto",
    source_language: "Idioma de origen",
    target_language: "Idioma de destino",
    select_source_language: "Selecciona idioma de origen",
    select_target_language: "Selecciona idioma de destino",
    split_method: "Método de segmentación",
    cancel: "Cancelar",
    continue: "Continuar",
    add_glossary_entry: "Agregar entrada al glosario",
    target_term: "Término objetivo",
    translation_meaning: "Traducción / Significado",
    add: "Agregar",
    close: "Cerrar",
    glossary_matches: "Coincidencias del glosario",
    local_settings_title: "Configuración local",
    local_settings_note:
      "La configuración de traducción automática y las claves API se guardan solo en este navegador y no se incluyen en los archivos JSON exportados.",
    app_language: "Idioma de la aplicación",
    translation_provider: "Proveedor de traducción",
    provider_none: "Ninguno",
    provider_mymemory: "MyMemory (sin cuenta)",
    provider_google: "Google Translate (clave API)",
    google_api_key: "Clave API de Google Cloud",
    mymemory_email: "Correo de MyMemory (opcional)",
    clear_keys: "Borrar claves",
    save_settings: "Guardar configuración",
    local_settings_saved: "Configuración local guardada.",
    local_settings_loaded: "Configuración local cargada.",
    local_settings_local_notice: "Esta configuración se guarda localmente en este navegador.",
    untitled_project: "Proyecto sin título",
    no_languages_set: "Idiomas no configurados",
    target_translation: "Traducción",
    write_translation_here: "Escribe la traducción aquí...",
    status_pending: "pendiente",
    status_translated: "traducido",
    status_prefix: "Estado",
    auto_translate_segment: "Traducir segmento automáticamente",
    translating: "Traduciendo...",
    select_segment_first: "Primero selecciona un segmento.",
    set_languages_first: "Primero configura idioma de origen y destino.",
    configure_mt_first: "Configura traducción automática en Configuración local primero.",
    selected_segment_no_source: "El segmento seleccionado no tiene texto de origen.",
    requesting_translation: "Solicitando traducción...",
    segment_translated: "Segmento traducido.",
    translation_failed: "La traducción falló.",
    no_translated_segments: "Aún no hay segmentos para exportar.",
    docx_export_unavailable: "La librería de exportación DOCX no está disponible. Recarga e inténtalo de nuevo.",
    could_not_export_docx: "No se pudo exportar DOCX.",
    project_saved: "Proyecto guardado.",
    invalid_project_file: "El archivo de proyecto seleccionado no es válido.",
    empty_document_file: "El archivo seleccionado no tiene contenido de texto legible.",
    start_new_project_confirm: "¿Iniciar un nuevo proyecto? Se perderán los cambios no guardados del proyecto actual.",
    onboarding_header: "Guía rápida",
    onboarding_step_counter: "Paso {current} de {total}",
    onboarding_back: "Atrás",
    onboarding_next: "Siguiente",
    onboarding_finish: "Finalizar",
    onboarding_skip: "Omitir",
  },
};

export const ONBOARDING_COPY = {
  en: {
    file_menu: { title: "File Actions", body: "Use File to import documents, open/save projects, and export finished translations." },
    segments: { title: "Segments", body: "Your document is split into segments here. Click any segment to work on it." },
    translation: { title: "Inline Translation", body: "After selecting a segment, the target text area appears inline so you can translate directly." },
    auto_translate: { title: "Auto-Translate", body: "If machine translation is configured, this button appears next to the selected segment." },
    glossary: { title: "Glossary", body: "Add term translations here to keep wording consistent across the project." },
    local_settings: { title: "Local Settings", body: "Choose translation provider and optional credentials here. These settings stay local and are not saved in project JSON exports." },
  },
  es: {
    file_menu: { title: "Acciones de archivo", body: "Usa Archivo para importar documentos, abrir/guardar proyectos y exportar traducciones terminadas." },
    segments: { title: "Segmentos", body: "Aquí se divide tu documento en segmentos. Haz clic en cualquier segmento para trabajar en él." },
    translation: { title: "Traducción en línea", body: "Después de seleccionar un segmento, el área de texto de destino aparece en línea para traducir directamente." },
    auto_translate: { title: "Traducción automática", body: "Si la traducción automática está configurada, este botón aparece junto al segmento seleccionado." },
    glossary: { title: "Glosario", body: "Agrega traducciones de términos aquí para mantener consistencia en todo el proyecto." },
    local_settings: { title: "Configuración local", body: "Elige proveedor de traducción y credenciales opcionales aquí. Esta configuración es local y no se guarda en JSON exportado." },
  },
};

export function resolvePreferredUiLanguage() {
  const stored = (localStorage.getItem(UI_LANGUAGE_STORAGE_KEY) || "").trim().toLowerCase();
  if (stored === "en" || stored === "es") {
    return stored;
  }
  const browserLangs = Array.isArray(navigator.languages) && navigator.languages.length
    ? navigator.languages
    : [navigator.language || ""];
  const first = String(browserLangs[0] || "").toLowerCase();
  return first.startsWith("es") ? "es" : "en";
}

export function translate(lang, key, vars = {}) {
  const table = UI_TEXT[lang] || UI_TEXT.en;
  const fallback = UI_TEXT.en[key] || key;
  const template = table[key] || fallback;
  return String(template).replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? ""));
}

export function getLanguageLabel(code, uiLanguage = "en") {
  if (!code) return "";
  const table = uiLanguage === "es" ? LANGUAGE_LABELS_ES : LANGUAGE_LABELS;
  return table[code] || LANGUAGE_LABELS[code] || code;
}

export function getLocalizedLanguageOptions(uiLanguage = "en") {
  const labels = uiLanguage === "es" ? LANGUAGE_LABELS_ES : LANGUAGE_LABELS;
  return Object.keys(LANGUAGE_LABELS)
    .map((code) => ({ code, label: labels[code] || LANGUAGE_LABELS[code] || code }))
    .sort((a, b) => a.label.localeCompare(b.label, uiLanguage === "es" ? "es" : "en", { sensitivity: "base" }));
}
